### ISSUE TITLE
"Cannot read property 'type' of null" when using transform-async-to-promises

### ISSUE THREAD

**Issue by robertknight** [robertknight/babel-plugin-mockable-imports#9]
**Steps to reproduce:**

Transpile the following code:

```js
export class Foo {}
export async function foo() {}
```

Using:

```
babel --plugins transform-async-to-promises,mockable-imports source.js
```

**Result:**

An error accessing `path.parent` when processing a `VariableDeclaration` node. This might be a bug in transform-async-to-promises.

```
TypeError: Cannot read property 'type' of null
    at PluginPass.VariableDeclaration (/Users/robert/hypothesis/repos/lms/node_modules/babel-plugin-mockable-imports/index.js:316:25)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:118:16)
```

**Workaround:**

Separate the function declaration and export like so:

```js
async function foo() {}

export { foo }
```

**Comment by robertknight** [comment]
We stopped using the transform-async-to-promises Babel plugin because async/await is now widely supported natively. Closing this as not-worth-fixing.
